### ISSUE TITLE
Update spent address import and export IXIs to support new spent address DBs

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1525] opened 2019-07-16 14:21 UTC
### Description
Update the IXIs that import and export to support new spent address DBs. Might just work. Might not work. :) 

### Motivation
Import and export IXIs support the new DB schema. 

### Requirements
- [ ] I can use the import IXI without with the merged local snapshot + spent address DB
- [ ] I can use the export IXI without with the merged local snapshot + spent address DB

**Comment by GalRogozinski** [comment] 2020-01-20 14:10
Since we have https://github.com/iotaledger/iri-ls-sa-merger/ I am closing this.
It may reopen if we see that we need this tool (maybe for regression tests)

**Closed** 2020-01-20 14:10 UTC
Labels: C-IXI, C-Spent Addresses
