### ISSUE TITLE
getInclusionStates with duplicate transactions raises NullPointerException

### ISSUE THREAD

**Issue by viossat** [iotaledger/iri#463] opened 2018-01-04 22:07 UTC
On 1.4.1.4:
Calling `getInclusionStates` with duplicate hashes in `transactions` raises an exception and leads to a HTTP error 500.

Reproduce:
`curl -v YOUR_FAVORTE_NODE -X POST -H 'X-IOTA-API-Version: 1' -d '{"command":"getInclusionStates","transactions":["AH99PQGSDUEPMYUIHKQCSJPRIQFGXOATZHKILEXCRPETO9LMGOQMQLNFFRXTQHCIKYCJAAWCKNHYA9999", "AH99PQGSDUEPMYUIHKQCSJPRIQFGXOATZHKILEXCRPETO9LMGOQMQLNFFRXTQHCIKYCJAAWCKNHYA9999"],"tips":["FJTVSFPKKPRPAWCDKFVNCEKJXNPIIJFXPDTSOVM9LLYXDCHPIOYXHRIRTLWTEHMQYFLH9VCQJ9NSA9999"]}'`

```
java.lang.NullPointerException: null
	at com.iota.iri.service.API.exhaustiveSearchWithinIndex(API.java:628) [iri.jar:na]
	at com.iota.iri.service.API.getNewInclusionStateStatement(API.java:613) [iri.jar:na]
	at com.iota.iri.service.API.process(API.java:237) [iri.jar:na]
	at com.iota.iri.service.API.processRequest(API.java:168) [iri.jar:na]
	at com.iota.iri.service.API.access$000(API.java:68) [iri.jar:na]
	at com.iota.iri.service.API$1.handleRequest(API.java:149) [iri.jar:na]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri.jar:na]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
```

**Comment by rajivshah3** [comment] 2018-01-05 22:57
+1 on 1.4.1.5:

```
01/05 22:52:25.268 [XNIO-1 task-48] ERROR com.iota.iri.service.API - API Exception: 
java.lang.NullPointerException: null
        at com.iota.iri.service.API.exhaustiveSearchWithinIndex(API.java:628) [iri-1.4.1.5.jar:na]
        at com.iota.iri.service.API.getNewInclusionStateStatement(API.java:613) [iri-1.4.1.5.jar:na]
        at com.iota.iri.service.API.process(API.java:237) [iri-1.4.1.5.jar:na]
        at com.iota.iri.service.API.processRequest(API.java:168) [iri-1.4.1.5.jar:na]
        at com.iota.iri.service.API.access$000(API.java:68) [iri-1.4.1.5.jar:na]
        at com.iota.iri.service.API$1.handleRequest(API.java:149) [iri-1.4.1.5.jar:na]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.4.1.5.jar:na]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.4.1.5.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```

**Comment by ralfr** [comment] 2018-01-12 12:21
+1 on 1.4.1.6: I see these a lot when Trinity Wallet testers connect to my nodes. I'd love for this to get fixed in IRI 1.4.1.7?!

**Comment by plenarius** [comment] 2018-01-27 03:53
Pardon me if this is way too simplistic but is there any harm to just doing this? Tested and appears to correct the issue but I'm not sure if it will create any larger issues.
```patch
diff --git a/src/main/java/com/iota/iri/service/API.java b/src/main/java/com/iota/iri/service/API.java
index 74ab3264..306a420e 100644
--- a/src/main/java/com/iota/iri/service/API.java
+++ b/src/main/java/com/iota/iri/service/API.java
@@ -607,7 +607,7 @@ public class API {
     }
 
     private AbstractResponse getNewInclusionStateStatement(final List<String> trans, final List<String> tps) throws Exception {
-        final List<Hash> transactions = trans.stream().map(Hash::new).collect(Collectors.toList());
+        final List<Hash> transactions = trans.stream().map(Hash::new).distinct().collect(Collectors.toList());
         final List<Hash> tips = tps.stream().map(Hash::new).collect(Collectors.toList());
         int numberOfNonMetTransactions = transactions.size();
         final int[] inclusionStates = new int[numberOfNonMetTransactions];```

**Comment by alon-e** [comment] 2018-01-27 21:50
thanks @plenarius,
the question here is what is the root cause. (the use of `indexOf` is one of them ;) )
also applying `distinct`, while a valid solution, violates the API contract:
the return value is a boolean array with the same length as `transactions`.

**Closed** 2018-01-28 21:27 UTC
