### ISSUE TITLE
IOTA IRI RocksDB error on a aarch64 VPS

### ISSUE THREAD

**Issue by artemisIrelia** [iotaledger/iri#559] opened 2018-02-26 17:39 UTC
I get the following error codes:
https://imgur.com/wM3j5o4
Any solution to this?

**Comment by muXxer** [comment] 2018-02-26 23:12
I have the same problem when i run "docker build" with the latest iri source from github on an aarch64 platform.

**Comment by muXxer** [comment] 2018-02-27 22:48
Here is the logfile of the docker build process: [docker-build.log](https://github.com/iotaledger/iri/files/1764962/docker-build.log)
The tests mostly fail because of RocksDB.

I think the following line is very important:
`java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni3010506048731292972.so: /tmp/librocksdbjni3010506048731292972.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
`

I think the problem is, that in the package "https://oss.sonatype.org/content/groups/public/org/rocksdb/rocksdbjni/5.7.3/rocksdbjni-5.7.3.jar", that is downloaded while building the iri source, there is no ".so" file for aarch64 platform included.

Any ideas?

**Comment by muXxer** [comment] 2018-02-27 23:38
Found the same issue here #312 and some workarounds. I will try it.

**Comment by jserv** [comment] 2018-02-28 21:06
@muXxer, Mark this issue as duplicated to #312?

**Comment by muXxer** [comment] 2018-02-28 21:16
Duplicate of #312

**Comment by muXxer** [comment] 2018-02-28 21:16
How can i do that? :)

**Comment by GalRogozinski** [comment] 2018-03-25 13:04
Closed as duplicate of #312

**Closed by GalRogozinski** 2018-03-25 13:04 UTC
Labels: duplicate
