### ISSUE TITLE
API Exception - iri 1.4.1.7

### ISSUE THREAD

**Issue by mettenian** [iotaledger/iri#493] opened 2018-01-22 09:12 UTC
I get this error when I try to login with IOTA Light Wallet 2.5.6 on iri 1.4.1.7 (milestone slightly behind):

`ERROR com.iota.iri.service.API - API Exception:
java.lang.NullPointerException: null
        at com.iota.iri.service.API.exhaustiveSearchWithinIndex(API.java:664) [iri-1.4.1.7.jar:na]
        at com.iota.iri.service.API.getNewInclusionStateStatement(API.java:649) [iri-1.4.1.7.jar:na]
        at com.iota.iri.service.API.process(API.java:241) [iri-1.4.1.7.jar:na]
        at com.iota.iri.service.API.processRequest(API.java:169) [iri-1.4.1.7.jar:na]
        at com.iota.iri.service.API.access$000(API.java:68) [iri-1.4.1.7.jar:na]
        at com.iota.iri.service.API$1.handleRequest(API.java:150) [iri-1.4.1.7.jar:na]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:208) [iri-1.4.1.7.jar:na]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [iri-1.4.1.7.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]`

**Comment by rajivshah3** [comment] 2018-01-24 03:48
Possible duplicate of #463

**Comment by alon-e** [comment] 2018-04-17 09:01
resolved by #506, reopen f not.

**Closed by alon-e** 2018-04-17 09:01 UTC
