### ISSUE TITLE
Node restarting problem

### ISSUE THREAD

**Issue by moodledidoodledi** [iotaledger/iri#5] opened 2016-11-08 22:01 UTC
Hi guys, Dom told me to create a new issue about the node restart problem a lot of people seem to have. Currently, if you restart your node, no tx are coming in. Afaik it doesn't connect to your neighbours anymore (Cfb said something like that) and it only works again if your neighbours restart their node. I think resolving this issue is quite important as many people have to restart their node on a daily basis. I think if this is solved the connectivity of the network would improve drastically as well as the ability to create confirming tx. Update: CfB told me this is because every time you restart you only get tx/connect to your neighbours if you do a new tx. I tried to do one and the node started up, but only some 20 tx showed up. If I spam, 20 tx show up in the console for each tx created

**Comment by Raganius** [comment] 2016-11-12 01:56
Indeed, sometimes it is really hard to make the node connect to its neighbours:
- I noticed that forwarding ports on my router makes no difference, when it "wants" to connect, it does, even without port forwarding. And sometimes it does not connect at all, even with the "correct router configurations".
- When the node is not connecting (even after the neighbours restart), the solution I found is to restart my node using a different port. I ask some of the neighbours to restart, updating my node's port. This way the connection is "instant". I can restart my node again, back with the standard port, and ask my neighbours to restart, updating my node's port. The connection will continue then.
- I believe this issue is caused by something between the nodes, the ISP, router, etc, because it affects only my home node: Connecting my VPS nodes is always really simple.

**Comment by davassi** [comment] 2016-11-23 10:50
I will fix it introducing a batch periodic check of the node Ips that will broadcast iP changes to local neighbours.

**Comment by todofixthis** [comment] 2016-12-06 00:37
Maybe related: #8

**Comment by m-d-f** [comment] 2016-12-10 00:01
@davassi from what I experienced and witnessed it's rather more simple. The IRI or wallet should re-resolve neighbors regularly that are noted with a dns address. Don't see why this should need a broadcast. I'm talking about this: https://iotatangle.slack.com/archives/general/p1481324954000999

**Comment by davassi** [comment] 2016-12-10 21:07
@m-d-f you are right. It's in the TODO list.

**Comment by davassi** [comment] 2016-12-12 17:04
@m-d-f There's a first Experimental implementation on dev branch. In order to activate it, use the -e flag.

**Comment by m-d-f** [comment] 2016-12-13 16:43
@davassi I was able to compile and make a basic test. When disconnecting the client and/or changing the address it seems to re-resolve the node in question after stgh. like 12 minutes and then with an interval of 30 minutes. I was able to reestablish a connection without restarting the node.

I was not able to test it further as I have not successfully explored how to run and manage the node without GUI due to time constraints. Should it be possible to run the GUI-Wallet with the IRI from the dev-branch?

**Comment by m-d-f** [comment] 2016-12-13 16:58
Seems not the case... will try to operate my node with all live neighbors and from cmdline later but anyhow seems to be step in right direction if not solution already.

**Comment by davassi** [comment] 2016-12-14 10:22
@m-d-f quite glad to hear that. We will do a new main-net release quite soon.

**Comment by davassi** [comment] 2016-12-16 08:52
Mainnet released. If this problem doesn't appear anymore I'm gonna close this issue down.

**Closed** 2016-12-19 15:06 UTC
