### ISSUE TITLE
Loading DB backup leads to "unexpected error while processing the seen milestones"

### ISSUE THREAD

**Issue by viossat** [iotaledger/iri#1715] opened 2020-01-20 17:35 UTC
### Bug description
Starting IRI with a DB baclup leads to errors and loading/syncing issues.

### IRI version
1.8.4

### Steps To Reproduce
1. Download `db-1300005.tar` from [dbfiles.iota.org](https://dbfiles.iota.org/?prefix=mainnet/iri/1.8.3/)
2. Extract the archive
3. Start IRI with default configuration

### Expected behaviour
IRI synchronizes on the latest milestone of the database.

### Actual behaviour
IRI never synchronizes and shows errors.

### Errors
I get those errors forever in loops. The hash after `unexpected error while analyzing the transaction` varies.
```
[Seen Milestones Retriever] ERROR SeenMilestonesRetrieverImpl:465 - unexpected error while processing the seen milestones
java.lang.ArrayIndexOutOfBoundsException: null
	at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_232]
	at com.iota.iri.model.persistables.Transaction.read(Transaction.java:103) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:155) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.storage.Tangle.load(Tangle.java:88) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.controllers.TransactionViewModel.fromHash(TransactionViewModel.java:132) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.service.milestone.impl.SeenMilestonesRetrieverImpl.lambda$retrieveSeenMilestones$0(SeenMilestonesRetrieverImpl.java:115) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597) ~[na:1.8.0_232]
	at com.iota.iri.service.milestone.impl.SeenMilestonesRetrieverImpl.retrieveSeenMilestones(SeenMilestonesRetrieverImpl.java:110) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.utils.thread.BoundedScheduledExecutorService.lambda$wrapTask$6(BoundedScheduledExecutorService.java:585) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]
[Latest Milestone Tracker] INFO  LatestMilestoneTrackerImpl:392 - Processing milestone candidates (267517 remaining) ...
[Latest Milestone Tracker] ERROR LatestMilestoneTrackerImpl:465 - error while analyzing the milestone candidates
com.iota.iri.service.milestone.MilestoneException: unexpected error while analyzing the transaction JY9HLQMCVAXTOOCNI9ASXPIKZZPDNESFPJTQDYSJECROA9ZKVQMSWKMXWGFJEBEFGRJMJYHTYJUGA9999
	at com.iota.iri.service.milestone.impl.LatestMilestoneTrackerImpl.processMilestoneCandidate(LatestMilestoneTrackerImpl.java:170) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.service.milestone.impl.LatestMilestoneTrackerImpl.analyzeMilestoneCandidates(LatestMilestoneTrackerImpl.java:342) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.service.milestone.impl.LatestMilestoneTrackerImpl.latestMilestoneTrackerThread(LatestMilestoneTrackerImpl.java:269) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.utils.thread.BoundedScheduledExecutorService.lambda$wrapTask$6(BoundedScheduledExecutorService.java:585) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]
Caused by: java.lang.ArrayIndexOutOfBoundsException: null
	at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_232]
	at com.iota.iri.model.persistables.Transaction.read(Transaction.java:103) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:155) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.storage.Tangle.load(Tangle.java:88) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.controllers.TransactionViewModel.fromHash(TransactionViewModel.java:132) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.service.milestone.impl.LatestMilestoneTrackerImpl.processMilestoneCandidate(LatestMilestoneTrackerImpl.java:168) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	... 10 common frames omitted
[main] INFO  i18n:549 - RESTEASY002225: Deploying javax.ws.rs.core.Application: class com.iota.iri.service.restserver.resteasy.RestEasy
[main] INFO  IRI$IRILauncher:139 - IOTA Node initialised correctly.
[Seen Milestones Retriever] ERROR SeenMilestonesRetrieverImpl:465 - unexpected error while processing the seen milestones
java.lang.ArrayIndexOutOfBoundsException: null
	at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_232]
	at com.iota.iri.model.persistables.Transaction.read(Transaction.java:103) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:155) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.storage.Tangle.load(Tangle.java:88) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.controllers.TransactionViewModel.fromHash(TransactionViewModel.java:132) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.service.milestone.impl.SeenMilestonesRetrieverImpl.lambda$retrieveSeenMilestones$0(SeenMilestonesRetrieverImpl.java:115) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597) ~[na:1.8.0_232]
	at com.iota.iri.service.milestone.impl.SeenMilestonesRetrieverImpl.retrieveSeenMilestones(SeenMilestonesRetrieverImpl.java:110) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.utils.thread.BoundedScheduledExecutorService.lambda$wrapTask$6(BoundedScheduledExecutorService.java:585) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]
[Latest Milestone Tracker] ERROR LatestMilestoneTrackerImpl:465 - error while analyzing the milestone candidates
com.iota.iri.service.milestone.MilestoneException: unexpected error while analyzing the transaction NAKUOKBECFCADRIODHVCBJXIILIQYGIZGOTQ9NSDHDKTSYAFQMLHDA99V9BXTWHTELIWPCFZONXNA9999
	at com.iota.iri.service.milestone.impl.LatestMilestoneTrackerImpl.processMilestoneCandidate(LatestMilestoneTrackerImpl.java:170) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.service.milestone.impl.LatestMilestoneTrackerImpl.analyzeMilestoneCandidates(LatestMilestoneTrackerImpl.java:342) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.service.milestone.impl.LatestMilestoneTrackerImpl.latestMilestoneTrackerThread(LatestMilestoneTrackerImpl.java:269) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.utils.thread.BoundedScheduledExecutorService.lambda$wrapTask$6(BoundedScheduledExecutorService.java:585) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]
Caused by: java.lang.ArrayIndexOutOfBoundsException: null
	at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_232]
	at com.iota.iri.model.persistables.Transaction.read(Transaction.java:103) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.get(RocksDBPersistenceProvider.java:155) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.storage.Tangle.load(Tangle.java:88) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.controllers.TransactionViewModel.fromHash(TransactionViewModel.java:132) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	at com.iota.iri.service.milestone.impl.LatestMilestoneTrackerImpl.processMilestoneCandidate(LatestMilestoneTrackerImpl.java:168) ~[iri-1.8.4-RELEASE.jar:1.8.4-RELEASE]
	... 10 common frames omitted
```
The `error while analyzing the milestone candidates` errors stop after few seconds. The `unexpected error while processing the seen milestones` errors continue to show up every seconds, even after processing all the milestone candidates.

**Comment by DyrellC** [comment] 2020-01-23 23:51
@galrogo The reason for this failure is that the release branch does not contain the merging of #1702 whereas the dev branch does. 1702 was merged at the same time as the release update and it contains the fix for the solid entrypoints. This in turn is causing the failure of the sync tests because they are reliant on the release docker rather than the dev docker.

**Comment by GalRogozinski** [comment] 2020-01-24 08:18
Woke up now and checked this out...
This is definitely not the case...

I performed the following commands on the cli
```
git checkout master
git hist -5
*   [2020-01-05] [fa79533] | Merge branch 'release-v1.8.4' {{Gal Rogozinski}}  (HEAD -> master, tag: v1.8.4-RELEASE, iotaledger-public/master)
|\  
| * [2020-01-05] [344b7d6] | update changelog {{Gal Rogozinski}}  (release-v1.8.4)
| * [2020-01-05] [07983a9] | up version to 1.8.4 {{Gal Rogozinski}} 
| * [2020-01-02] [0b188c2] | change docs {{Gal Rogozinski}}  (iotaledger-gal-public/patch-solid-entrypoints, patch-solid-entrypoints)
| * [2020-01-02] [1774615] | Only add tails as for solid entry points {{Gal Rogozinski}} 
|/  
```
As you can see the commits from #1702 are there

I think what confused you was the way this `hotfix` was created. We prtetty much adopted the `Gitflow` as described here: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

Meaning we create a branch from `master` and then merged it to `master` w/o a PR and to `dev` with a PR.

**Comment by GalRogozinski** [comment] 2020-01-24 08:48
On Discord @muXxer  said that it might be the RocksDb upgrade...
It makes less sense to me because in a private chat @DyrellC said that running the latest `dev` solves the problem (this is how his above findings came to be). But maybe this can still be investigated?

Anyhows, @viossat, you can try running from `dev` like @DyrellC did ti
You may need to convert your LS with this tool though: 
https://github.com/iotaledger/iri-ls-sa-merger/

Easy docker for it is: docker run -v </path/to/iri/node/data/dir>:/data iotacafe/iri-ls-sa-merger

Note: A good guy named Kryzstof will try to test the `dev` fix. If it works well he will update :-)

**Comment by taraszka** [comment] 2020-01-24 09:23
Thanks @GalRogozinski -  yes, I will try to test it today.

**Comment by viossat** [comment] 2020-01-24 12:08
@GalRogozinski The `dev` branch is running fine.

**Comment by GalRogozinski** [comment] 2020-01-24 13:25
This means that on the upcoming release it will be fixed
We just need to figure out why :sweat_smile:

**Comment by GalRogozinski** [comment] 2020-01-24 17:54
I think it has just hit me...
It is possible that someone uploaded a db with an experimental version of IRI to db.files.iota.org?
Becuase we have #1635 in `dev`, which breaks backwards compatability...

@sadjy?

**Comment by DyrellC** [comment] 2020-01-24 18:04
@GalRogozinski Ok after further investigation it is indeed caused by a rocksdb issue. The release/master branches do not include the upgrade to 6.3.6 or one of the changes Brord made following that update that fixes a missing variable issue that comes up from the rocksdb update itself.

**Comment by DyrellC** [comment] 2020-01-24 18:06
There might be another issue missing but master and release have a huge gap in commits from October 12 to December 29 and a lot changed during that time

**Comment by DyrellC** [comment] 2020-01-24 18:07
Nvm looks like there's still something else going on along with that. I'm fairly convinced that it has to do with all the changes to RocksDB for the size in bytes merges that make it work on dev but not on master

**Comment by GalRogozinski** [comment] 2020-01-25 20:32
Did you try looking at the data being read?
I saw those exceptions happen when a db from `dev` that truncated the transactions was used by a release IRI

**Comment by GalRogozinski** [comment] 2020-01-27 12:29
Ok, we found out that a patch for 1.8.4 that included dev commits ran on the machine. Once we fix `dbfiles.iota.org/` we will close the issue

**Closed** 2020-03-31 16:24 UTC
Labels: T-Bug
