### ISSUE TITLE
TCP neighbor connection freezes

### ISSUE THREAD

**Issue by michi6383** [iotaledger/iri#521] opened 2018-01-30 13:50 UTC
Dear devs, I hope I don't bother you now with low level TCP issues. In the #fullnodes channel several full node admins have the same problem. A TCP connection between two nodes (neighbors) suddenly freezes. Only a IRI restart would solve this. A tcpdump shows nothing.
Here an example.
![tcp_prob_1](https://user-images.githubusercontent.com/1423424/35569570-b47b9eb6-05cc-11e8-84c2-af3f5b57234c.png)
If someone has the same problem. Please comment!

Thank you very much. Sincerely,
Michael

**Comment by pompomJuice** [comment] 2018-01-30 15:25
This is my theory:

https://github.com/iotaledger/iri/blob/8886df6e305e2a1c58f7a9c6a564b05fbadc4c92/src/main/java/com/iota/iri/network/replicator/ReplicatorSourceProcessor.java#L78

I am 100% sure TCP is totally mental

**Comment by curVV** [comment] 2018-01-30 16:29
Having same issue. Used to restart once a day but now every couple of hours or so tx flow between half my neighbours and my node comes to a halt. We're never sure who's node is the cause, but it's either one or the other that fixes it by restarting iri.

**Comment by pompomJuice** [comment] 2018-01-30 17:20
Actually that line is fine. 

I misunderstood it.

**Comment by pompomJuice** [comment] 2018-01-30 19:10
@michi6383 

Try [this](https://github.com/pompomJuice/iri/commit/bfc18c70de97792739911cb64d846963db50e086) patch. Help me test it. See if things go better.

If you find success I might make a PR.

**Comment by pompomJuice** [comment] 2018-01-30 20:58
https://github.com/iotaledger/iri/blob/8886df6e305e2a1c58f7a9c6a564b05fbadc4c92/src/main/java/com/iota/iri/network/replicator/ReplicatorSinkProcessor.java#L82

That is the line causing the race condition with a neighbor that was just dropped from `ReplicatorSinkProcessor`. 

If you look at the previous line: 
https://github.com/iotaledger/iri/blob/8886df6e305e2a1c58f7a9c6a564b05fbadc4c92/src/main/java/com/iota/iri/network/replicator/ReplicatorSinkProcessor.java#L81
is a blocking call with a timeout of 10 seconds. Plenty of time to cause a race. So by the time the call ends a new sink might have been created causing two sink threads to be popping messages and sending them at the same time.

**Comment by michi6383** [comment] 2018-01-31 09:40
###### RESTARTED IRI MANUALLY
Jan 30 09:14:24 vmd24512 IRI[1073]: 01/30 09:14:24.971 [main] INFO  com.iota.iri.network.Node - -> Adding neighbor : abc.com/a.b.c.d:15600
Jan 30 09:14:25 vmd24512 IRI[1073]: 01/30 09:14:25.756 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'abc.com' with 'a.b.c.d'
Jan 30 09:44:28 vmd24512 IRI[1073]: 01/30 09:44:28.395 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'abc.com' with 'a.b.c.d'
Jan 30 09:44:28 vmd24512 IRI[1073]: 01/30 09:44:28.395 [pool-2-thread-3] INFO  com.iota.iri.network.Node - abc.com seems fine.
Jan 30 10:14:31 vmd24512 IRI[1073]: 01/30 10:14:31.575 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'abc.com' with 'a.b.c.d'
Jan 30 10:14:31 vmd24512 IRI[1073]: 01/30 10:14:31.575 [pool-2-thread-3] INFO  com.iota.iri.network.Node - abc.com seems fine.
Jan 30 10:44:33 vmd24512 IRI[1073]: 01/30 10:44:33.595 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'abc.com' with 'a.b.c.d'
Jan 30 10:44:33 vmd24512 IRI[1073]: 01/30 10:44:33.595 [pool-2-thread-3] INFO  com.iota.iri.network.Node - abc.com seems fine.
Jan 30 11:14:35 vmd24512 IRI[1073]: 01/30 11:14:35.696 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'abc.com' with 'a.b.c.d'
...
Jan 31 06:16:36 vmd24512 IRI[1073]: 01/31 06:16:36.789 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'abc.com' with 'a.b.c.d'
Jan 31 06:16:36 vmd24512 IRI[1073]: 01/31 06:16:36.790 [pool-2-thread-3] INFO  com.iota.iri.network.Node - abc.com seems fine.
Jan 31 06:46:58 vmd24512 IRI[1073]: 01/31 06:46:58.870 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'abc.com' with 'a.b.c.d'
Jan 31 06:46:58 vmd24512 IRI[1073]: 01/31 06:46:58.870 [pool-2-thread-3] INFO  com.iota.iri.network.Node - abc.com seems fine.
Jan 31 07:17:01 vmd24512 IRI[1073]: 01/31 07:17:01.228 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'abc.com' with 'a.b.c.d'
Jan 31 07:17:01 vmd24512 IRI[1073]: 01/31 07:17:01.228 [pool-2-thread-3] INFO  com.iota.iri.network.Node - abc.com seems fine.
Jan 31 07:47:03 vmd24512 IRI[1073]: 01/31 07:47:03.295 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'abc.com' with 'a.b.c.d'
Jan 31 07:47:03 vmd24512 IRI[1073]: 01/31 07:47:03.295 [pool-2-thread-3] INFO  com.iota.iri.network.Node - abc.com seems fine.
###### RESTARTED IRI MANUALLY
Jan 31 08:07:27 vmd24512 IRI[12765]: 01/31 08:07:27.626 [main] INFO  com.iota.iri.network.Node - -> Adding neighbor : abc.com/a.b.c.d:15600
![tcp_prob_2](https://user-images.githubusercontent.com/1423424/35615648-1491f3bc-0673-11e8-910e-ce7b326aa38a.png)

**Comment by alon-e** [comment] 2018-04-16 16:27
@michi6383 does this issue still occur with the latest `dev` branch?
if not, please close the issue, thanks!

**Closed** 2018-06-07 08:49 UTC
Labels: C-Network, T-Bug
