### ISSUE TITLE
rocksDB initialization exception on FreeBSD

### ISSUE THREAD

**Issue by criticaltech** [iotaledger/iri#545] opened 2018-02-18 18:28 UTC
Grü'ßi!
To sponsore a PoW Node i fired up IRI on a fresh FBSD 11.1 on Azure but it fails with a rocksDB init exception:

02/19 02:19:51.409 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.2.1
02/19 02:20:17.658 [main] INFO  com.iota.iri.IRI - You have set the debug flag. To enable debug output, you need to uncomment the DEBUG appender in the source tree at iri/src/main/resources/logback.xml and re-package iri.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
        at com.iota.iri.Iota.initializeTangle(Iota.java:201)
        at com.iota.iri.Iota.init(Iota.java:92)
        at com.iota.iri.IRI.main(IRI.java:73)
Caused by: java.lang.UnsupportedOperationException: Cannot determine JNI library name for ARCH='amd64' OS='freebsd' name='rocksdb'
        at org.rocksdb.util.Environment.getJniLibraryName(Environment.java:66)
        at org.rocksdb.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:19)
        ... 6 more
02/19 02:20:19.108 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
02/19 02:20:25.133 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node:
java.lang.NullPointerException: null
        at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.2.1.jar:na]
        at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.2.1.jar:na]
        at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri-1.4.2.1.jar:na]
        at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:247) ~[iri-1.4.2.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]

**Comment by GalRogozinski** [comment] 2018-03-26 10:52
Will reference this issue on RocksDb repo

**Comment by jakubcech** [comment] 2018-06-21 09:59
Duplicate of https://github.com/iotaledger/iri/issues/396 thanks!

**Closed by jakubcech** 2018-06-21 09:59 UTC
Labels: C-DB
